config/routes.rb
Rails.application.routes.draw do
    resources :visits
    resources :visitors
    resources :units
    resources :sectors
    resources :users

  devise_for :users, :path => "auth"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "visits#index"
end

app/models/visitor.rb
class Visitor < ApplicationRecord
  validates :cpf, presence: true, uniqueness: true, :mask => "999.999.999-99"
  validates :name, presence: true, length: { minimum: 3, maximum: 100 }
  validates :rg, presence: true, uniqueness: true, :mask => "99.999.999-9"
  validates :phone, presence: true, :mask => "(99) 99999-9999"
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  before_action :set_visitor, only: %i[ show edit update destroy ]

  # GET /visitors or /visitors.json
  def index
    @visitors = Visitor.accessible_by(current_ability)
  end

  # GET /visitors/1 or /visitors/1.json
  def show
  end

  # GET /visitors/new
  def new
    @visitor = Visitor.new
  end

  # GET /visitors/1/edit
  def edit
  end

  # POST /visitors or /visitors.json
  def create
    @visitor = Visitor.new(visitor_params)

    respond_to do |format|
      if @visitor.save
        format.html { redirect_to visitor_url(@visitor), notice: "Visitor was successfully created." }
        format.json { render :show, status: :created, location: @visitor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @visitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visitors/1 or /visitors/1.json
  def update
    respond_to do |format|
      if @visitor.update(visitor_params)
        format.html { redirect_to visitor_url(@visitor), notice: "Visitor was successfully updated." }
        format.json { render :show, status: :ok, location: @visitor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @visitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visitors/1 or /visitors/1.json
  def destroy
    @visitor.destroy

    respond_to do |format|
      format.html { redirect_to visitors_url, notice: "Visitor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visitor
      @visitor = Visitor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def visitor_params
      params.require(:visitor).permit(:cpf, :name, :rg, :phone)
    end
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/views/visitors/_form.html.erb
<%= form_with(model: visitor, html: { data: { controller: "masks" } }) do |form| %>
  <% if visitor.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(visitor.errors.count, "error") %> prohibited this visitor from being saved:</h2>

      <ul>
        <% visitor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, placeholder: "Nome" %>
  </div>

  <div>
    <%= form.label :cpf, style: "display: block" %>
    <%= form.text_field :cpf, placeholder: "000.000.000-00", data: { masks_target: 'cpf' } %>
  </div>

  <div>
    <%= form.label :rg, style: "display: block" %>
    <%= form.text_field :rg, placeholder: "00.000.000-0", data: { masks_target: 'rg' } %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone, placeholder: "(00) 00000-0000", :data => { masks_target: 'phone'} %>
  </div>

  <button type="submit" class="w-full mt-4 px-4 py-2 bg-blue-600 text-sm text-white rounded">
    Save visitor
  </button>
<% end %>

app/views/visitors/_visitor.html.erb
<div id="<%= dom_id visitor %>">
  <p>
    <strong>Cpf:</strong>
    <%= visitor.cpf %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= visitor.name %>
  </p>

  <p>
    <strong>Rg:</strong>
    <%= visitor.rg %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= visitor.phone %>
  </p>

</div>

app/views/visitors/edit.html.erb
<a href="<%= visitors_path %>">
  <button class="bg-blue-500 hover:bg-blue-700 text-sm text-white py-2 px-4 rounded">
    Back
  </button>
</a>

<h1 class="text-center text-lg">Editing visitor</h1>

<div class="flex flex-col items-center gap-2">
  <%= render "form", visitor: @visitor %>
</div>

<a href="/visitors/<%= @visitor.id %>">
  <button class="bg-blue-500 hover:bg-blue-700 text-sm text-white py-2 px-4 rounded">
    Show visitor
  </button>
</a>

app/views/visitors/index.html.erb
<% if can? :create, Visitor %>
  <div class="flex justify-end">
    <a href="<%= new_visitor_path %>">
      <button class="bg-blue-500 hover:bg-blue-700 text-sm text-white py-2 px-4 rounded">
        New Visitor
      </button>
    </a>
  </div>
<% end %>

<div id="visitors" class="flex flex-col items-center gap-2">
  <% @visitors.each do |visitor| %>
    <div class="flex flex-row w-80 justify-between items-center p-4 bg-white rounded">
      <div id="<%= dom_id visitor %>">
        <p>
          <%= visitor.name %>
        </p>
        <p class="text-sm">
          <%= visitor.cpf %>
        </p>
        <p class="text-sm">
          <%= visitor.rg %>
        </p>
        <p class="text-sm">
          <%= visitor.phone %>
        </p>
      </div>
      <a href="/visitors/<%= visitor.id %>">
        <button class="bg-blue-500 hover:bg-blue-700 text-sm text-white py-2 px-4 rounded">
          Show
        </button>
      </a>
    </div>
  <% end %>
</div>

app/views/visitors/new.html.erb
<a href="<%= visitors_path %>">
  <button class="bg-blue-500 hover:bg-blue-700 text-sm text-white py-2 px-4 rounded">
    Back
  </button>
</a>

<h1 class="text-center text-lg">New visitor</h1>

<div class="flex flex-col items-center gap-2">
  <%= render "form", visitor: @visitor %>
</div>

app/views/visitors/show.html.erb
<a href="<%= visitors_path %>">
  <button class="bg-blue-500 hover:bg-blue-700 text-sm text-white py-2 px-4 rounded">
    Back
  </button>
</a>

<div id="<%= dom_id @visitor %>" class="flex flex-col items-center gap-2">
  <p>
    <strong>Name:</strong>
    <%= @visitor.name %>
  </p>
  <p class="text-sm">
    <strong>Cpf:</strong>
    <%= @visitor.cpf %>
  </p>
  <p class="text-sm">
    <strong>Rg:</strong>
    <%= @visitor.rg %>
  </p>
  <p class="text-sm">
    <strong>Phone:</strong>
    <%= @visitor.phone %>
  </p>
</div>

<div class="flex flex-row gap-4 pt-2 text-sm">
  <% if can? :read, @visitor %>
    <a href="<%= edit_visitor_path(@visitor) %>">
      <button class="bg-blue-500 hover:bg-blue-700 text-sm text-white py-2 px-4 rounded">
        Edit
      </button>
    </a>
  <% end %>

   <% if can? :destroy, @visitor %>
    <%= button_to "Destroy", @visitor, method: :delete, class: "bg-red-500 hover:bg-red-700 text-sm text-white py-2 px-4 rounded" %>
  <% end %>
</div>