config/routes.rb
Rails.application.routes.draw do
    resources :visits
    resources :visitors
    resources :units
    resources :sectors
    resources :users

  devise_for :users, :path => "auth"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "visits#index"
end

app/models/visit.rb
class Visit < ApplicationRecord
  belongs_to :visitor
  belongs_to :sector
  belongs_to :user, optional: true
  validates :visitor, presence: true
  validates :sector, presence: true
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  before_action :set_visit, only: %i[ show edit update destroy ]
  before_action :set_visitors, only: %i[ new edit create update ]
  before_action :set_sectors, only: %i[ new edit create update ]
  before_action :set_employees, only: %i[ new edit create update ]

  # GET /visits or /visits.json
  def index
    @visits = Visit.accessible_by(current_ability)
  end

  # GET /visits/1 or /visits/1.json
  def show
  end

  # GET /visits/new
  def new
    @visit = Visit.new
  end

  # GET /visits/1/edit
  def edit
  end

  # POST /visits or /visits.json
  def create
    @visit = Visit.new(visit_params)

    respond_to do |format|
      if @visit.save
        format.html { redirect_to visit_url(@visit), notice: "Visit was successfully created." }
        format.json { render :show, status: :created, location: @visit }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visits/1 or /visits/1.json
  def update
    respond_to do |format|
      if @visit.update(visit_params)
        format.html { redirect_to visit_url(@visit), notice: "Visit was successfully updated." }
        format.json { render :show, status: :ok, location: @visit }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visits/1 or /visits/1.json
  def destroy
    @visit.destroy

    respond_to do |format|
      format.html { redirect_to visits_url, notice: "Visit was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visit
      @visit = Visit.find(params[:id])
    end

    def set_visitors
      @visitors = Visitor.pluck(:name, :id)
    end

    def set_sectors
      @sectors = Sector.pluck(:id, :name, :unit_id).map do |sector|
        [sector[1] + " | " + Unit.find(sector[2]).name, sector[0]]
      end
    end

    def set_employees
      @employees = User.where(role: "employee").pluck(:name, :id)
    end

    # Only allow a list of trusted parameters through.
    def visit_params
      params.require(:visit).permit(:visitor_id, :sector_id, :user_id)
    end
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/visits/_form.html.erb
<%= form_with(model: visit) do |form| %>
  <% if visit.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(visit.errors.count, "error") %> prohibited this visit from being saved:</h2>

      <ul>
        <% visit.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :visitor_id, style: "display: block" %>
    <%= form.collection_select :visitor_id, @visitors, :last, :first %>
  </div>

  <div>
    <%= form.label :sector_id, style: "display: block" %>
    <%= form.collection_select :sector_id, @sectors, :last, :first %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.collection_select :user_id, @employees, :last, :first, include_blank: true %>
  </div>

  <button type="submit" class="w-full mt-4 px-4 py-2 bg-blue-600 text-sm text-white rounded">
    Save Visit
  </button>
<% end %>

app/views/visits/_visit.html.erb
<div id="<%= dom_id visit %>">
  <p>
    <strong>Visitor:</strong>
    <%= visit.visitor_id %>
  </p>

  <p>
    <strong>Sector:</strong>
    <%= visit.sector_id %>
  </p>

  <p>
    <strong>User:</strong>
    <%= visit.user_id %>
  </p>

</div>

app/views/visits/edit.html.erb
<a href="<%= visits_path %>">
  <button class="bg-blue-500 hover:bg-blue-700 text-sm text-white py-2 px-4 rounded">
    Back
  </button>
</a>

<h1 class="text-center text-lg">Editing visit</h1>

<div class="flex flex-col items-center gap-2">
  <%= render "form", visit: @visit %>
</div>

<a href="/visits/<%= @visit.id %>">
  <button class="bg-blue-500 hover:bg-blue-700 text-sm text-white py-2 px-4 rounded">
    Show visit
  </button>
</a>

app/views/visits/index.html.erb
<% if can? :create, Visit %>
  <div class="flex justify-end">
    <a href="<%= new_visit_path %>">
      <button class="bg-blue-500 hover:bg-blue-700 text-sm text-white py-2 px-4 rounded">
        New Visit
      </button>
    </a>
  </div>
<% end %>

<div id="visits" class="flex flex-col items-center gap-2">
  <% @visits.each do |visit| %>
    <div class="flex flex-row w-80 justify-between items-center p-4 bg-white rounded">
      <div id="<%= dom_id visit %>">
        <p>
          <%= visit.visitor.name %>
        </p>
        <p class="text-sm">
          <%= visit.visitor.cpf %>
        </p>
        <p class="text-sm">
          <%= visit.sector.name %> | <%= visit.sector.unit.name %>
        </p>
        <% if visit.user.present? %>
          <p class="text-sm">
            <%= visit.user.name %>
          </p>
        <% end %>
      </div>
      <a href="/visits/<%= visit.id %>">
        <button class="bg-blue-500 hover:bg-blue-700 text-sm text-white py-2 px-4 rounded">
          Show
        </button>
      </a>
    </div>
  <% end %>
</div>

app/views/visits/new.html.erb
<a href="<%= visits_path %>">
  <button class="bg-blue-500 hover:bg-blue-700 text-sm text-white py-2 px-4 rounded">
    Back
  </button>
</a>

<h1 class="text-center text-lg">New visit</h1>

<div class="flex flex-col items-center gap-2">
  <%= render "form", visit: @visit %>
</div>

app/views/visits/show.html.erb
<a href="<%= visits_path %>">
  <button class="bg-blue-500 hover:bg-blue-700 text-sm text-white py-2 px-4 rounded">
    Back
  </button>
</a>

<div id="<%= dom_id @visit %>">
  <p>
    <strong>
      Visitor:
    </strong>
    <%= @visit.visitor.name %>
  </p>
  <% if @visit.user.present? %>
    <p class="text-sm">
      <strong>
        Employee:
      </strong>
      <%= @visit.user.name %>
    </p>
  <% end %>
  <p class="text-sm">
    <strong>
      Sector:
    </strong>
    <%= @visit.sector.name %>
  </p>
  <p class="text-sm">
    <strong>
      Unit:
    </strong>
    <%= @visit.sector.unit.name %>
  </p>
</div>

<div class="flex flex-row gap-4 pt-2 text-sm">
  <% if can? :edit, @visit %>
    <a href="<%= edit_visit_path(@visit) %>">
      <button class="bg-blue-500 hover:bg-blue-700 text-sm text-white py-2 px-4 rounded">
        Edit
      </button>
    </a>
  <% end %>

  <% if can? :destroy, @visit %>
    <%= button_to "Destroy", @visit, method: :delete, class: "bg-red-500 hover:bg-red-700 text-sm text-white py-2 px-4 rounded" %>
  <% end %>
</div>