config/routes.rb
Rails.application.routes.draw do
    resources :visits
    resources :visitors
    resources :units
    resources :sectors
    resources :users

  devise_for :users, :path => "auth"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "visits#index"
end

app/views/shared/_navbar.html.erb
<nav class="flex flex-row gap-2 justify-between">
    <ul class="flex flex-row items-center">
        <% if can? :read, Unit %>
            <% if current_page? units_path %>
                <li class="p-4 bg-blue-300">Units</li>
            <% else %>
                <a href="/units" class="h-full">
                    <li class="p-4 hover:bg-blue-100">Units</li>
                </a>
            <% end %>
        <% end %>
        <% if can? :read, Sector %>
            <% if current_page? sectors_path %>
                <li class="p-4 bg-blue-300">Sectors</li>
            <% else %>
                <a href="/sectors" class="h-full">
                    <li class="p-4 hover:bg-blue-100">Sectors</li>
                </a>
            <% end %>
        <% end %>
        <% if can? :read, Visit %>
            <% if current_page? visits_path %>
                <li class="p-4 bg-blue-300">Visits</li>
            <% else %>
                <a href="/visits" class="h-full">
                    <li class="p-4 hover:bg-blue-100">Visits</li>
                </a>
            <% end %>
        <% end %>
        <% if can? :read, Visitor %>
            <% if current_page? visitors_path %>
                <li class="p-4 bg-blue-300">Visitors</li>
            <% else %>
                <a href="/visitors" class="h-full">
                    <li class="p-4 hover:bg-blue-100">Visitors</li>
                </a>
            <% end %>
        <% end %>
        <% if can? :read, User %>
            <% if current_page? users_path %>
                <li class="p-4 bg-blue-300">Users</li>
            <% else %>
                <a href="/users" class="h-full">
                    <li class="p-4 hover:bg-blue-100">Users</li>
                </a>
            <% end %>
        <% end %>
    </ul>

    <div class="flex flex-row items-center gap-2 p-2">
        <% if user_signed_in? %>
            <p class="text-sm">
                <%= current_user.name %>
            </p>
            <p class="text-sm italic">
                <%= current_user.role.capitalize %>
            </p>
            <%= button_to "Sair", destroy_user_session_path, method: :delete, class: "w-full px-4 py-2 bg-blue-600 text-sm text-white rounded" %>
        <% else %>
            <%= link_to "Entrar", new_user_session_path, class: "w-full px-4 py-2 bg-blue-600 text-sm text-white rounded" %>
        <% end %>
    </div>
</nav>