config/routes.rb
Rails.application.routes.draw do
    resources :visits
    resources :visitors
    resources :units
    resources :sectors
    resources :users

  devise_for :users, :path => "auth"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "visits#index"
end

app/models/unit.rb
class Unit < ApplicationRecord
  has_many :sectors
  validates :name, presence: true, uniqueness: true, length: { minimum: 3, maximum: 100 }
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  before_action :set_unit, only: %i[ show edit update destroy ]

  # GET /units or /units.json
  def index
    @units = Unit.all
  end

  # GET /units/1 or /units/1.json
  def show
  end

  # GET /units/new
  def new
    @unit = Unit.new
  end

  # GET /units/1/edit
  def edit
  end

  # POST /units or /units.json
  def create
    @unit = Unit.new(unit_params)

    respond_to do |format|
      if @unit.save
        format.html { redirect_to unit_url(@unit), notice: "Unit was successfully created." }
        format.json { render :show, status: :created, location: @unit }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /units/1 or /units/1.json
  def update
    respond_to do |format|
      if @unit.update(unit_params)
        format.html { redirect_to unit_url(@unit), notice: "Unit was successfully updated." }
        format.json { render :show, status: :ok, location: @unit }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1 or /units/1.json
  def destroy
    @unit.destroy

    respond_to do |format|
      format.html { redirect_to units_url, notice: "Unit was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unit
      @unit = Unit.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def unit_params
      params.require(:unit).permit(:name)
    end
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/units/_form.html.erb
<%= form_with(model: unit) do |form| %>
  <% if unit.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(unit.errors.count, "error") %> prohibited this unit from being saved:</h2>

      <ul>
        <% unit.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <button type="submit" class="w-full mt-4 px-4 py-2 bg-blue-600 text-sm text-white rounded">
    Save Unit
  </button>
<% end %>

app/views/units/edit.html.erb
<a href="<%= units_path %>">
  <button class="bg-blue-500 hover:bg-blue-700 text-sm text-white py-2 px-4 rounded">
    Back
  </button>
</a>

<h1 class="text-center text-lg">Editing unit</h1>

<div class="flex flex-col items-center gap-2">
  <%= render "form", unit: @unit %>
</div>

<a href="/units/<%= @unit.id %>">
  <button class="bg-blue-500 hover:bg-blue-700 text-sm text-white py-2 px-4 rounded">
    Show unit
  </button>
</a>

app/views/units/index.html.erb
<% if can? :create, Unit %>
  <div class="flex justify-end">
    <a href="<%= new_unit_path %>">
      <button class="bg-blue-500 hover:bg-blue-700 text-sm text-white py-2 px-4 rounded">
        New Unit
      </button>
    </a>
  </div>
<% end %>

<div id="units" class="flex flex-col items-center gap-2">
  <% @units.each do |unit| %>
    <div class="flex flex-row w-80 justify-between items-center p-4 bg-white rounded">
      <div id="<%= dom_id unit %>">
        <p>
          <%= unit.name %>
        </p>
      </div>
      <a href="/units/<%= unit.id %>">
        <button class="bg-blue-500 hover:bg-blue-700 text-sm text-white py-2 px-4 rounded">
          Show
        </button>
      </a>
    </div>
  <% end %>
</div>

app/views/units/new.html.erb
<a href="<%= units_path %>">
  <button class="bg-blue-500 hover:bg-blue-700 text-sm text-white py-2 px-4 rounded">
    Back
  </button>
</a>

<h1 class="text-center text-lg">New unit</h1>

<div class="flex flex-col items-center gap-2">
  <%= render "form", unit: @unit %>
</div>

app/views/units/show.html.erb
<a href="<%= units_path %>">
  <button class="bg-blue-500 hover:bg-blue-700 text-sm text-white py-2 px-4 rounded">
    Back
  </button>
</a>

<div id="<%= dom_id @unit %>" class="flex flex-col items-center gap-2">
  <p>
    <strong>
      Nome:
    </strong>
    <%= @unit.name %>
  </p>
</div>

<div class="flex flex-row gap-4 pt-2 text-sm">
  <% if can? :edit, @unit %>
    <a href="<%= edit_unit_path(@unit) %>">
      <button class="bg-blue-500 hover:bg-blue-700 text-sm text-white py-2 px-4 rounded">
        Edit
      </button>
    </a>
  <% end %>

  <% if can? :destroy, @unit %>
    <%= button_to "Destroy", @unit, method: :delete, class: "bg-red-500 hover:bg-red-700 text-sm text-white py-2 px-4 rounded" %>
  <% end %>
</div>